### ISSUE TITLE
Assign subfleets to ranks

### ISSUE THREAD

**Issue by nabeelio** [nabeelio/phpvms#100]
## few notes

* subfleets aren't rolled up from the lower ranks, all need to be assigned

## todo 

- [x] Allow assigning of subfleets to ranks (copy-paste the code from the flights edit page)
- [x] Setting to restrict the front-end aircraft selection to the current rank
- [x] API call that can read all the aircraft allowed for a rank, e.g.`/api/ranks/{ID}/fleet`
- [ ] API call to get the allowable fleet for a user e.g. `/api/user/fleet`
