### ISSUE TITLE
Add config.php in root on install

### ISSUE THREAD

**Issue by nabeelio** [nabeelio/phpvms#156]
Add it to get parsed and override any configs, vs adding them all manually in several places in the env.php file. Mainly for forward compatibility and easier to upgrade, don't need to touch any of the files in the `config/` folder. E.g:

```php
return [
  # overrides the app.php config file
  'app' => [
    'name' => 'phpVMS Airlines',
  ],
];
```

### tasks

- See `ServiceProvider::mergeConfigFrom`
- See `\Illuminate\Support\Arr`
- [x] create stub in installer
  - move database/mail settings
- [x] move phpvms settings
- [x] read and parse in `AppServiceProvider` (replace the `local.config.php` entry)
- [x] docs

Sample file: https://gist.github.com/nabeelio/a93b062121a29647efe43b3508ccffe8
