### ISSUE TITLE
Setup cron tasks

### ISSUE THREAD

**Issue by nabeelio** [nabeelio/phpvms#95]
- Investigate how scheduled tasks work (https://laravel.com/docs/5.5/scheduling)
- Instructions for configuring page-load driven cron, or script to run via cronjob
  - call `artisan schedule:run`
  - run by chance per-request
- Way to add scheduled tasks via modules?
  
## initial work

- [x] Cleanup `$commands` var in the Kernel, not needed
- [x] Organize scheduled tasks in their own namespace
  - `Console/Scheduled`
  - Add to `commands()` method in `Kernel.php`

## tasks

- [x] Pilot leave #96
- [ ] Clean up cancelled PIREPs after X days
- [ ] Recalculate user hours/total flights
- [x] Stats table population
- [x] Financials (might need adding tasks via modules)
